application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

#new handlers should go ABOVE the catch all url (.*)
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
